---

name: Deploy Slips

on: 
  push: 
    branches: 
      - main
    paths:
      - 'cards/standard/**'

jobs:
  dewit: 
    runs-on: "ubuntu-latest"

    steps:
      ## https://github.com/actions/checkout
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: sync to s3
        run: |
          aws s3 sync ./cards/standard/ s3://res.starwarsccg.org/vkit/cards/standard/ --exclude '.git/*' --exclude '.github/*' --exclude 'node_modules/*' --exclude README.md --exclude package-lock.json --exclude package.json --delete
          echo "Cloudfront Invalidation"
          aws cloudfront create-invalidation --distribution-id E4R02360UW5RJ --paths "/vkit/cards/standard/"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

